### ISSUE TITLE
Renewal errors

### ISSUE THREAD

**Issue by GaloisGhost** [kelunik/acme-client#64]
Registration failed (1)
'/usr/local/php56/bin/php' 'acme-client/bin/acme' 'setup' '--server' 'letsencrypt' '--storage' '/home/user/acme-client/data' '--email' 'xxxxx@example.com'

exception 'Amp\Dns\TimeoutException' with message 'Name resolution timed out for example.com in /home/user/acme-client/vendor/amphp/dns/lib/DefaultResolver.php:271

Next exception 'Kelunik\Acme\AcmeException' with message 'Dns query for an MX record on 'example.com' failed for the following reason: Name resolution timed out for example.com' in /home/user/acme-client/src/Commands/Setup.php:87

It worked 2 weeks ago. So obviously something has changed on the server however it's a shared host and I do not know what.  Any help will be much appreciated

**Comment by kelunik** [comment]
Something timed out, which might be a network hickup, did you try it again?

**Comment by X-Coder** [comment]
Had the same error.

For me the issue was in the windows registry. There was an invalid nameserver set, pointed to 127.0.0.1, which I don't use any more and also removed it long ago. Even the interface which it belongs to, does not exists any more, because I removed it too. But windows registry still listed it.

The issue is in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces. Check NameServer and DhcpNameServer properties in all subkeys and remove or correct the ones which are wrong. The first one found will win, no matter if its available or not.

I think vendor\amphp\dns\lib\DefaultResolver.php#loadResolvConf function should check if the nameserver is available before using it. Or find a better way in windows to get the correct nameserver because the interfaces in this subkey where not consistent with the the interfaces listed elsewhere, also windows itself did not use this nameserver found by this function.

**Comment by kelunik** [comment]
Moved to https://github.com/amphp/dns/issues/70.
